services:
    nginx:
        image: nginx:1.25
        ports:
            - '8080:80'
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './:/var/www/html'

    database:
        image: mariadb:11.5
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data: